Repository isaacmsl/bora-pagar, pull requests merged in 2024-01, with the labels that each got.

#25 Feat/subject endpoint
  backend/src/main/java/ufrn/imd/boraPagar/core/AbstractController.java
  backend/src/main/java/ufrn/imd/boraPagar/core/AbstractModel.java
  backend/src/main/java/ufrn/imd/boraPagar/core/AbstractRepository.java
  backend/src/main/java/ufrn/imd/boraPagar/core/AbstractService.java
  backend/src/main/java/ufrn/imd/boraPagar/subject/SubjectController.java
  backend/src/main/java/ufrn/imd/boraPagar/subject/SubjectModel.java
  backend/src/main/java/ufrn/imd/boraPagar/subject/SubjectRepository.java
  backend/src/main/java/ufrn/imd/boraPagar/subject/SubjectService.java
  backend/src/test/java/ufrn/imd/boraPagar/subject/SubjectTests.java
Labels: enhancement

#26 feat: equiv, req, coreq optionals but txt
  backend/src/main/java/ufrn/imd/boraPagar/subject/SubjectModel.java
  backend/src/test/java/ufrn/imd/boraPagar/subject/SubjectTests.java
Labels: enhancement

#27 fix: AbstractRepository findAllActive (isActive)
  backend/src/main/java/ufrn/imd/boraPagar/core/AbstractRepository.java
Labels: bug

#28 feat: Subject new attribute 'modality'
  backend/src/main/java/ufrn/imd/boraPagar/subject/SubjectController.java
  backend/src/main/java/ufrn/imd/boraPagar/subject/SubjectModalityType.java
  backend/src/main/java/ufrn/imd/boraPagar/subject/SubjectModel.java
  backend/src/main/java/ufrn/imd/boraPagar/subject/SubjectRepository.java
  backend/src/main/java/ufrn/imd/boraPagar/subject/SubjectService.java
  backend/src/test/java/ufrn/imd/boraPagar/subject/SubjectTests.java
Labels: enhancement

#36 Feat/oauth google
  backend/pom.xml
  backend/src/main/java/ufrn/imd/boraPagar/BoraPagarApplication.java
  backend/src/main/java/ufrn/imd/boraPagar/config/SecurityConfig.java
  backend/src/main/java/ufrn/imd/boraPagar/user/CustomUserDetailsService.java
  backend/src/main/java/ufrn/imd/boraPagar/user/UserController.java
  backend/src/main/java/ufrn/imd/boraPagar/user/UserModel.java
  backend/src/main/java/ufrn/imd/boraPagar/user/UserRepository.java
  backend/src/main/java/ufrn/imd/boraPagar/user/UserService.java
  backend/src/main/resources/application.yml
  backend/src/test/java/ufrn/imd/boraPagar/user/UserTests.java
Labels: enhancement

#40 Feat/find all by username
  backend/src/main/java/ufrn/imd/boraPagar/user/UserController.java
  backend/src/main/java/ufrn/imd/boraPagar/user/UserRepository.java
  backend/src/main/java/ufrn/imd/boraPagar/user/UserService.java
  backend/src/test/java/ufrn/imd/boraPagar/user/UserTests.java
Labels: enhancement

#48 Feat/verify google auth
  backend/pom.xml
  backend/src/main/java/ufrn/imd/boraPagar/config/SecurityConfig.java
  backend/src/main/java/ufrn/imd/boraPagar/core/AbstractController.java
  backend/src/main/java/ufrn/imd/boraPagar/core/AbstractService.java
  backend/src/main/java/ufrn/imd/boraPagar/subject/SubjectController.java
  backend/src/main/java/ufrn/imd/boraPagar/subject/SubjectService.java
  backend/src/main/java/ufrn/imd/boraPagar/user/GoogleUserWrapper.java
  backend/src/main/java/ufrn/imd/boraPagar/user/UserController.java
  backend/src/main/java/ufrn/imd/boraPagar/user/UserService.java
  backend/src/main/resources/application.yml
Labels: enhancement

#51 feat: insomnia json
  backend/isomnia.json
Labels: documentation, enhancement

#42 feat: cache Subject findAll (decrease response time)
  backend/pom.xml
  backend/src/main/java/ufrn/imd/boraPagar/BoraPagarApplication.java
  backend/src/main/java/ufrn/imd/boraPagar/subject/SubjectService.java
Labels: enhancement

#56 Endpoint pode retornar várias disciplinas
  backend/src/main/java/ufrn/imd/boraPagar/subject/SubjectController.java
  backend/src/main/java/ufrn/imd/boraPagar/subject/SubjectRepository.java
  backend/src/main/java/ufrn/imd/boraPagar/subject/SubjectService.java
  backend/src/test/java/ufrn/imd/boraPagar/subject/SubjectTests.java
Labels: bug

#55 Feat/pinia auth store
  frontend/src/components/UserProfile.vue
  frontend/src/stores/auth.ts
  frontend/src/views/SearchUsers.vue
  frontend/src/views/SubjectList.vue
Labels: enhancement

#57 Removing .yarn and .lock files
  frontend/.gitignore
  frontend/.vscode/extensions.json
  frontend/.yarn/install-state.gz
  frontend/.yarn/sdks/eslint/bin/eslint.js
  frontend/.yarn/sdks/eslint/lib/api.js
  frontend/.yarn/sdks/eslint/lib/unsupported-api.js
  frontend/.yarn/sdks/eslint/package.json
  frontend/.yarn/sdks/integrations.yml
  frontend/.yarn/sdks/prettier/bin/prettier.cjs
  frontend/.yarn/sdks/prettier/index.cjs
  frontend/.yarn/sdks/prettier/package.json
  frontend/.yarn/sdks/typescript/bin/tsc
  frontend/.yarn/sdks/typescript/bin/tsserver
  frontend/.yarn/sdks/typescript/lib/tsc.js
  frontend/.yarn/sdks/typescript/lib/tsserver.js
  frontend/.yarn/sdks/typescript/lib/tsserverlibrary.js
  frontend/.yarn/sdks/typescript/lib/typescript.js
  frontend/.yarn/sdks/typescript/package.json
  frontend/package-lock.json
Labels: bug

#60 Creating UserMenu component
  frontend/src/components/UserMenu.vue
  frontend/src/views/SearchUsers.vue
  frontend/src/views/SubjectList.vue
Labels: enhancement

#66 Axios API
  frontend/.env
  frontend/src/services/UserService.ts
  frontend/src/views/SearchUsers.vue
  frontend/tsconfig.json
Labels: enhancement

#63 Feat/find all pagination
  backend/src/main/java/ufrn/imd/boraPagar/core/AbstractController.java
  backend/src/main/java/ufrn/imd/boraPagar/core/AbstractRepository.java
  backend/src/main/java/ufrn/imd/boraPagar/core/AbstractService.java
  backend/src/main/java/ufrn/imd/boraPagar/subject/SubjectController.java
  backend/src/main/java/ufrn/imd/boraPagar/subject/SubjectService.java
  backend/src/test/java/ufrn/imd/boraPagar/subject/SubjectTests.java
  backend/src/test/java/ufrn/imd/boraPagar/user/UserTests.java
Labels: enhancement

#64 Feat/add name attribute
  backend/Insomnia.json
  backend/isomnia.json
  backend/src/main/java/ufrn/imd/boraPagar/user/GoogleUserWrapper.java
  backend/src/main/java/ufrn/imd/boraPagar/user/UserController.java
  backend/src/main/java/ufrn/imd/boraPagar/user/UserModel.java
  backend/src/main/java/ufrn/imd/boraPagar/user/UserRepository.java
  backend/src/main/java/ufrn/imd/boraPagar/user/UserService.java
  backend/src/test/java/ufrn/imd/boraPagar/user/UserTests.java
Labels: enhancement

#59 feat: Dockerfile backend to host on render
  backend/.gitignore
  backend/Dockerfile
  backend/src/main/resources/application.yml
Labels: enhancement

#70 Fix/user tests find all name
  backend/src/main/java/ufrn/imd/boraPagar/user/UserModel.java
  backend/src/test/java/ufrn/imd/boraPagar/user/UserTests.java
Labels: bug

#68 feat: SubjectModel DBRef interestedUsers
  backend/src/main/java/ufrn/imd/boraPagar/subject/SubjectModel.java
  backend/src/test/java/ufrn/imd/boraPagar/subject/SubjectTests.java
Labels: enhancement

#73 fix: SubjectModel @DBRef lazy true
  backend/src/main/java/ufrn/imd/boraPagar/subject/SubjectModel.java
Labels: bug

#76 Feat/json view admin default
  backend/src/main/java/ufrn/imd/boraPagar/core/AbstractController.java
  backend/src/main/java/ufrn/imd/boraPagar/core/AbstractModel.java
  backend/src/main/java/ufrn/imd/boraPagar/core/Views.java
  backend/src/main/java/ufrn/imd/boraPagar/user/UserModel.java
  backend/src/main/resources/application.yml
Labels: enhancement

#82 Adding debounce to search of users
  frontend/src/util/debounce.ts
  frontend/src/views/SearchUsers.vue
Labels: enhancement

#81 (Feat) Role implementation
  backend/src/main/java/ufrn/imd/boraPagar/core/AbstractService.java
  backend/src/main/java/ufrn/imd/boraPagar/user/RoleEnum.java
  backend/src/main/java/ufrn/imd/boraPagar/user/UserController.java
  backend/src/main/java/ufrn/imd/boraPagar/user/UserModel.java
  backend/src/main/java/ufrn/imd/boraPagar/user/UserRepository.java
  backend/src/main/java/ufrn/imd/boraPagar/user/UserService.java
  backend/src/test/java/ufrn/imd/boraPagar/user/UserTests.java
Labels: enhancement

#84 refact: AbstractService uses GOOGLE_CLIENT_ID env var
  backend/src/main/java/ufrn/imd/boraPagar/core/AbstractService.java
Labels: enhancement

#87 Fix/correct duplicated find all by total hours
  backend/src/main/java/ufrn/imd/boraPagar/core/AbstractModel.java
  backend/src/main/java/ufrn/imd/boraPagar/subject/SubjectController.java
Labels: bug

#85 feat: UserProfile btns nav
  frontend/src/components/UserProfile.vue
Labels: enhancement

#89 Feat/front back subject pagination
  frontend/src/services/SubjectService.ts
  frontend/src/types/PageSubject.ts
  frontend/src/types/Subject.ts
  frontend/src/views/SubjectList.vue
Labels: enhancement

#93 fix: overflow-hidden SubjectList no auth
  frontend/src/views/SubjectList.vue
Labels: enhancement

#99 Feat/paginate user methods find all
  backend/src/main/java/ufrn/imd/boraPagar/user/UserController.java
  backend/src/main/java/ufrn/imd/boraPagar/user/UserRepository.java
  backend/src/main/java/ufrn/imd/boraPagar/user/UserService.java
  backend/src/test/java/ufrn/imd/boraPagar/user/UserTests.java
Labels: enhancement

#101 Feat/search users front pagination
  frontend/src/services/UserService.ts
  frontend/src/types/PageUser.ts
  frontend/src/views/SearchUsers.vue
Labels: enhancement

#95 Feat/welcome route back front
  backend/src/main/java/ufrn/imd/boraPagar/user/UserController.java
  backend/src/main/java/ufrn/imd/boraPagar/user/UserService.java
  frontend/src/services/UserService.ts
  frontend/src/stores/auth.ts
Labels: enhancement

#100 Feat/subject filters
  backend/src/main/java/ufrn/imd/boraPagar/subject/SubjectModel.java
  frontend/src/assets/departments.json
  frontend/src/components/CustomSelect.vue
  frontend/src/main.ts
  frontend/src/services/SubjectService.ts
  frontend/src/types/SubjectFilters.ts
  frontend/src/views/SubjectList.vue
Labels: enhancement

#104 Removing duplicates from departments json
  frontend/src/assets/departments.json
  frontend/src/components/CustomSelect.vue
Labels: bug

#111 Feat/subjects user view
  backend/src/main/java/ufrn/imd/boraPagar/subject/SubjectController.java
  backend/src/main/java/ufrn/imd/boraPagar/subject/SubjectRepository.java
  backend/src/main/java/ufrn/imd/boraPagar/subject/SubjectService.java
  backend/src/main/java/ufrn/imd/boraPagar/user/UserController.java
  backend/src/main/java/ufrn/imd/boraPagar/user/UserService.java
  frontend/src/router/index.ts
  frontend/src/services/SubjectService.ts
  frontend/src/services/UserService.ts
  frontend/src/views/SubjectsUser.vue
Labels: enhancement

#110 Adding interested user pictures
  frontend/src/components/SubjectListItem.vue
Labels: enhancement

#109 Feat/find all by name and department method
  backend/src/main/java/ufrn/imd/boraPagar/subject/SubjectController.java
  backend/src/main/java/ufrn/imd/boraPagar/subject/SubjectRepository.java
  backend/src/main/java/ufrn/imd/boraPagar/subject/SubjectService.java
  backend/src/test/java/ufrn/imd/boraPagar/subject/SubjectTests.java
Labels: enhancement

#115 (Bug) Removing findAllBy name and department
  backend/src/main/java/ufrn/imd/boraPagar/subject/SubjectController.java
  backend/src/main/java/ufrn/imd/boraPagar/subject/SubjectRepository.java
  backend/src/main/java/ufrn/imd/boraPagar/subject/SubjectService.java
  backend/src/test/java/ufrn/imd/boraPagar/subject/SubjectTests.java
Labels: bug

#113 Feat/click user see his subjects
  frontend/src/components/SubjectListItem.vue
  frontend/src/components/UserListItem.vue
  frontend/src/util/navigation.ts
Labels: enhancement

#117 feat: integrating filters with backend
  frontend/src/services/SubjectService.ts
  frontend/src/views/SubjectList.vue
Labels: enhancement

#131 Improving responsiveness
  frontend/src/assets/base.css
  frontend/src/components/Button.vue
  frontend/src/components/SubjectListItem.vue
  frontend/src/components/UserListItem.vue
  frontend/src/components/UserProfile.vue
  frontend/src/views/SearchUsers.vue
  frontend/src/views/SubjectList.vue
  frontend/src/views/SubjectsUser.vue
Labels: enhancement

#158 fix: subject list height
  frontend/src/views/SubjectList.vue
Labels: bug

#161 fix: component updates on route change
  frontend/src/views/SubjectsUser.vue
Labels: bug

#164 feat: adding text ellipsis
  frontend/src/components/SubjectListItem.vue
Labels: enhancement

#156 Update README.md
  README.md
Labels: documentation

#170 fix: portuguese errors
  README.md
Labels: bug, documentation

#167 Feat/exception handling
  backend/pom.xml
  backend/src/main/java/ufrn/imd/boraPagar/core/AbstractService.java
  backend/src/main/java/ufrn/imd/boraPagar/core/ApplicationConstants.java
  backend/src/main/java/ufrn/imd/boraPagar/exceptions/ResourceNotFoundException.java
  backend/src/main/java/ufrn/imd/boraPagar/exceptions/handler/ExceptionResponse.java
  backend/src/main/java/ufrn/imd/boraPagar/exceptions/handler/GlobalExceptionHandler.java
  backend/src/main/java/ufrn/imd/boraPagar/subject/SubjectController.java
  backend/src/main/java/ufrn/imd/boraPagar/subject/SubjectRepository.java
  backend/src/main/java/ufrn/imd/boraPagar/subject/SubjectService.java
  backend/src/main/java/ufrn/imd/boraPagar/user/GoogleUserWrapper.java
  backend/src/main/java/ufrn/imd/boraPagar/user/UserController.java
  backend/src/main/java/ufrn/imd/boraPagar/user/UserRepository.java
  backend/src/main/java/ufrn/imd/boraPagar/user/UserService.java
  backend/src/test/java/ufrn/imd/boraPagar/exception/ExceptionTests.java
Labels: enhancement

#166 feat: secrets-template.yml resources backend
  backend/src/main/resources/secrets-template.yml
Labels: enhancement

#165 Initial Open Api Config
  backend/pom.xml
  backend/src/main/java/ufrn/imd/boraPagar/config/OpenApiConfig.java
Labels: documentation, enhancement

#150 Feat/ordenation by alphabetical name
  backend/src/main/java/ufrn/imd/boraPagar/user/UserController.java
  backend/src/main/java/ufrn/imd/boraPagar/user/UserRepository.java
  backend/src/main/java/ufrn/imd/boraPagar/user/UserService.java
  backend/src/test/java/ufrn/imd/boraPagar/user/UserTests.java
Labels: enhancement

#180 fix: click on image
  frontend/src/components/SubjectListItem.vue
  frontend/src/components/UserSmallAvatar.vue
Labels: bug

#185 fix: isPresent user on userPersistNewUserOrUpdateExisting
  backend/src/main/java/ufrn/imd/boraPagar/user/GoogleUserWrapper.java
Labels: bug

#168 fix: `pagarei` button gets unaligned
  frontend/src/components/Button.vue
  frontend/src/components/SubjectListItem.vue
Labels: bug

#120 Feat/add user friends
  backend/Insomnia.json
  backend/src/main/java/ufrn/imd/boraPagar/user/UserController.java
  backend/src/main/java/ufrn/imd/boraPagar/user/UserModel.java
  backend/src/main/java/ufrn/imd/boraPagar/user/UserService.java
  backend/src/test/java/ufrn/imd/boraPagar/user/UserFriendsTests.java
Labels: enhancement
